

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./linguaphoto
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DEBUG: "true"
      AWS_REGION: " us-east-1" # Environment variables for DynamoDB
      AWS_ACCESS_KEY_ID: "your-access-key-id"
      AWS_SECRET_ACCESS_KEY: "your-secret-access-key"
      DYNAMODB_ENDPOINT: "http://dynamodb:8002" # Local DynamoDB endpoint
      REDIS_URL: "redis://redis:6379" # Redis connection URL

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8002:8000"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000

  redis:
    image: redis
    ports:
      - "6379:6379"