# Composes DynamoDB Local, the DynamoDB Admin UI, and Redis
version: '3.7'

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000

  redis:
    image: redis
    ports:
      - "6379:6379"
