name: Deploy to AWS App Runner

# Trigger this workflow on any push to the 'main' branch
on:
  push:
    branches:
      - master

jobs:
  # Job for deploying the backend service
  deploy-backend:
    name: Deploy Backend to AWS App Runner
    runs-on: ubuntu-latest  # Run on the latest version of Ubuntu

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3  # GitHub Action to checkout the code

    # Step 2: Set up AWS CLI with necessary credentials
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2  # GitHub Action to configure AWS credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}          # AWS Access Key ID stored as a GitHub secret
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Access Key stored as a GitHub secret
        aws-region: us-east-1                        # AWS Region stored as a GitHub secret

    # Step 3: Deploy the backend service to AWS App Runner
    - name: Deploy Backend
      run: |
        # AWS CLI command to update the backend service in AWS App Runner
        aws apprunner update-service \
          --service-arn $(aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='${{ secrets.APP_RUNNER_SERVICE_NAME_BACKEND }}'].ServiceArn | [0]" --output text) \
          --source-configuration SourceCodeRepository={"RepositoryUrl": "${{ secrets.REPOSITORY_URL_BACKEND  }}", "SourceCodeVersion": {"Type": "BRANCH", "Value": "master"}}

  # Job for deploying the frontend service
  deploy-frontend:
    name: Deploy Frontend to AWS App Runner
    runs-on: ubuntu-latest  # Run on the latest version of Ubuntu

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3  # GitHub Action to checkout the code

    # Step 2: Set up AWS CLI with necessary credentials
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2  # GitHub Action to configure AWS credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}          # AWS Access Key ID stored as a GitHub secret
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Access Key stored as a GitHub secret
        aws-region: ${{ secrets.AWS_REGION }}                        # AWS Region stored as a GitHub secret

    # Step 3: Deploy the frontend service to AWS App Runner
    - name: Deploy Frontend
      run: |
        # AWS CLI command to update the frontend service in AWS App Runner
        aws apprunner update-service \
          --service-arn $(aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='${{ secrets.APP_RUNNER_SERVICE_NAME_FRONTEND }}'].ServiceArn | [0]" --output text) \
          --source-configuration SourceCodeRepository={"RepositoryUrl": "${{ secrets.REPOSITORY_URL_FRONTEND }}", "SourceCodeVersion": {"Type": "BRANCH", "Value": "master"}}